export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const ADD_MOVIE = "ADD_MOVIE";
// export const INITIAL_DATA_REQUEST = "INITIAL_DATA_REQUEST";
// export const INITIAL_DATA_SUCCESS = "INITIAL_DATA_SUCCESS";
// export const INITIAL_DATA_FAILURE = "INITIAL_DATA_FAILURE";
